#!/bin/sh
base=$(pwd)
name="pyer/$(basename $base):5.0"
container_name="running_php"
[ -d site ] || mkdir site
docker stop $container_name
docker rm $container_name
docker rmi $name 
docker build --rm -t $name .
docker run -d -p 9000:9000 -v /srv/php:/home --link running_postgres:postgres --name $container_name $name
