#!/bin/sh
base=$(pwd)
[ -r data ] && mkdir data
[ -r data/psql ] && mkdir data/psql
[ -r data/log ] && mkdir data/log
[ -r data/php ] && mkdir data/php
cp nginx_php/site/index.php data/php/
docker run -d -p 5433:5432 -v $base/data/psql:/home --name php_db pyer/postgres:9.6
docker run -d -p 9000:9000 -v $base/data/php:/home -v $base/data/log:/var/log       --link php_db:postgres --name running_php   pyer/php-fpm:5.0
docker run -d -p 80:80     -v $base/data/php:/home -v $base/data/log:/var/log/nginx --link running_php:php --name running_nginx pyer/nginx_php:1.8
