USE mysql;
FLUSH PRIVILEGES;
DELETE FROM mysql.user;
GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' IDENTIFIED BY 'root' WITH GRANT OPTION;
CREATE USER IF NOT EXISTS 'wp' IDENTIFIED BY 'wp';
CREATE DATABASE IF NOT EXISTS wordpress CHARACTER SET utf8 COLLATE utf8_general_ci;
GRANT ALL ON wordpress.* to 'wp'@'%' IDENTIFIED BY 'wp';
GRANT ALL PRIVILEGES ON wordpress.* to 'wp';
FLUSH PRIVILEGES;
