#!/bin/sh
base=$(pwd)
name="pyer/$(basename $base)"
container_name="nginx_8081"
docker stop $container_name
docker rm $container_name
docker rmi $name 
docker build --rm -t $name .
docker run -d -v /opt/site:/var/www/html --publish 8081:80 --network php-net --name $container_name $name
