#!/bin/sh
docker stop httpd
docker rm httpd
mkdir -p logs
docker run -d -p 80:80 -p 443:443 -v "$PWD/htdocs":/usr/local/apache2/htdocs -v "$PWD/conf":/usr/local/apache2/conf -v "$PWD/logs":/usr/local/apache2/logs --name httpd httpd:2.4.54-alpine
